### ISSUE TITLE
dont change font size title week and day

### ISSUE THREAD

**Issue by rajaEBA** [ali-sardari/PersianRangeDatePicker#3]
hi ali,
I use this dialog, but I cant change font size, plz help me.

   datePickerDialog.setTextSizeTitle(10);
        datePickerDialog.setTextSizeWeek(10);

**Comment by ali-sardari** [comment]
Hi
Thank you for your feedback.

`implementation 'com.github.ali-sardari:PersianRangeDatePicker:1.2.0'`

`
datePickerDialog.setTextSizeWeek(12.0f);
datePickerDialog.setTextSizeDate(14.0f);`
