### ISSUE TITLE
راستچین شده ماه ها

### ISSUE THREAD

**Issue by iman-hp** [ali-sardari/PersianRangeDatePicker#5]
سلام ممنون بابت کتابخونه خوبتون لطفا اگر مقدور هست ماه ها را راستچین کنید یعنی به چپ تعویض بشن تشکر.

**Comment by ali-sardari** [comment]
سلام
تشکر از نظر مثبت شما.
دکمه های ماه بعد و قبل جابجا شدن.
موفق باشید.

**Comment by iman-hp** [comment]
ممنون بابت پشتیبانی خوبتون

‫‪Ali Sardari‬‏ <‪notifications@github.com‬‏> در تاریخ جمعه ۳۰ اوت ۲۰۱۹
ساعت ۲۱:۰۵ نوشت:‬
