### ISSUE TITLE
استفاده به عنوان Fragment

### ISSUE THREAD

**Issue by naser8646** [ali-sardari/PersianRangeDatePicker#6]
سلام ممنون بخار این کتابخانه خوبتون
آیا میشه این تقویم رو به صورت فرگمنت و استفاده کرد یعنی به حالت دیالوگ باز نشه و به صورت ثابت روی صفخه باشه و ازش استفاده کرد

**Comment by ali-sardari** [comment]
سلام
بله میشه ولی احتمالا نیاز دارید که یه سری تغییرات ظاهری انجام بدید.
سعی میکنم یه نمونه ساده بفرستم.

**Comment by naser8646** [comment]
سلام
باتشکر بسیار زیاد ممنون میشم کد رو بزارید
فقط یفرمایید خیلی باید صبر کنم

**Comment by ali-sardari** [comment]
<com.sardari.daterangepicker.customviews.DateRangeCalendarView
        android:id="@+id/calendar"
        android:layout_centerHorizontal="true"
        android:layout_alignParentBottom="true"
        android:layout_width="300dp"
        android:layout_height="300dp"/>

**Comment by ali-sardari** [comment]
DateRangeCalendarView calendar = findViewById(R.id.calendar);
        calendar.setCalendarListener(new DateRangeCalendarView.CalendarListener() {
            @Override
            public void onDateSelected(PersianCalendar date) {
                
            }

            @Override
            public void onDateRangeSelected(PersianCalendar startDate, PersianCalendar endDate) {

            }

            @Override
            public void onCancel() {

            }
        });

**Comment by naser8646** [comment]
واقعا ازتون ممنونم
